using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace server.Models{
    public class SurveyResponse
    {
        public int Id { get; set; }  // Changed from string to int, will be auto-generated by DB
        
        [ForeignKey("SurveyTemplate")]
        public int SurveyTemplateId { get; set; }  // Links to which survey
        public SurveyTemplate? SurveyTemplate { get; set; }  // Navigation property
        
        public int ContactId { get; set; }  // Who answered it
        public List<Answer>? Answers { get; set; }  // Their answers
        public DateTime StartedAt { get; set; }
        public DateTime? CompletedAt { get; set; }
    }
}