namespace server.Models{
    public class SurveyResponse
    {
        public int Id { get; set; }  // Changed from string to int, will be auto-generated by DB
        public int SurveyId { get; set; }  // Links to which survey
        public int ContactId { get; set; }  // Who answered it
        public List<Answer>? Answers { get; set; }  // Their answers
        public DateTime StartedAt { get; set; }
        public DateTime? CompletedAt { get; set; }
    }
}